### ISSUE TITLE
hover effects

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/mcauley2017#34]
Look at this website, Github. As you move your mouse over things you can click on, they usually change colour, or get an underline -- that's a hover effect.

Hover effects help people understand how to use your site.

On our site, add a hover effect to every interactive thing (every button, link and input).

You add them using css by making a css rule that only applies when the mouse is over something.

```css
input:hover {
  background-color: red;
}
```

You add `:hover` to the css selector (the first line) to make the rules only apply when the thing has the mouse pointer over it.

So in this exampe, I've said "when the user has their mouse pointer over an input, make its background color red."

*Check*: a cool hover effect on every interactive thing on the whole site

## active effects

When you click on something, it becomes `active`. You can also add active effects to things:

```css
button:active {
  background-color: orange;
}
```
